config/routes.rb
Rails.application.routes.draw do
  resources :twitter_users

  resources :feeds_users

  resources :feeds

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root to:'feeds_users#index'

end

app/models/twitter_user.rb
class TwitterUser < ActiveRecord::Base
end

app/controllers/twitter_users_controller.rb
class TwitterUsersController < ApplicationController
  before_action :set_twitter_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /twitter_users
  # GET /twitter_users.json
  def index

    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "ZlKRQXJDicbNHXjqIr0dllZsc"
      config.consumer_secret     = "JOh0eAtpdHY0uSsaQbPDUFL8TUYygOtaEwCV6cRQ6y2KXFiK6U"
      config.access_token        = "197092649-CihsuA5dYOZDy86CRxLu9kwDDkvdHfhXQi8xQiIn"
      config.access_token_secret = "UCIHoGPegZn4Pwk2opnsJd22Mu7Aenpgm3fa8ylsJvnrc"
    end

    twitter_users = TwitterUser.where(user_id: current_user)

    @all_tweets = []

     twitter_users.each do |twitter_user|

      client.user_timeline(twitter_user.twitter_id)[0..11].each  do |tweet|
        @all_tweets.push(id:twitter_user.twitter_id, tweet:tweet.full_text,
                         fav_count:tweet.favorite_count, rt_count:tweet.retweet_count)
      end

     end
    @all_tweets.shuffle!
  end

  def retweet

  end

  def favorite

  end

  # GET /twitter_users/1
  # GET /twitter_users/1.json
  def show
  end

  # GET /twitter_users/new
  def new
    @twitter_user = TwitterUser.new
  end

  # GET /twitter_users/1/edit
  def edit
  end

  # POST /twitter_users
  # POST /twitter_users.json
  def create
    @twitter_user = TwitterUser.new(twitter_user_params)

    respond_to do |format|

      if @twitter_user.save
        format.html { redirect_to twitter_users_path, notice: 'Twitter user was successfully created.' }
        format.json { render :show, status: :created, location: @twitter_user }
      else
        format.html { render :new }
        format.json { render json: @twitter_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitter_users/1
  # PATCH/PUT /twitter_users/1.json
  def update
    respond_to do |format|
      if @twitter_user.update(twitter_user_params)
        format.html { redirect_to @twitter_user, notice: 'Twitter user was successfully updated.' }
        format.json { render :show, status: :ok, location: @twitter_user }
      else
        format.html { render :edit }
        format.json { render json: @twitter_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitter_users/1
  # DELETE /twitter_users/1.json
  def destroy
    @twitter_user.destroy
    respond_to do |format|
      format.html { redirect_to twitter_users_url, notice: 'Twitter user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter_user
      @twitter_user = TwitterUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twitter_user_params
      params.require(:twitter_user).permit(:user_id, :twitter_id)
    end
end

app/helpers/twitter_users_helper.rb
module TwitterUsersHelper
end

app/views/twitter_users/_form.html.erb
<%= form_for(@twitter_user) do |f| %>
  <% if @twitter_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitter_user.errors.count, "error") %> prohibited this twitter_user from being saved:</h2>

      <ul>
      <% @twitter_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.hidden_field :user_id, {:value => current_user.id} %>
    <div class="field">
      <%= f.label "Twitter Handles" %><br/>

      <%= f.select(:twitter_id, TwitterHandle.all.collect { |p| ['@' + p.twitter_id, TwitterHandle.find_by_twitter_id(p.twitter_id).twitter_id]}) %>
      <%= f.hidden_field :user_id, {:value => current_user.id} %>

    </div>
    <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitter_users/edit.html.erb
<h1>Editing Twitter User</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitter_user %> |
<%= link_to 'Back', twitter_users_path %>

app/views/twitter_users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="btn-group">
  <img class="btn-group" src= 'https://g.twimg.com/dev/documentation/image/Twitter_logo_blue_48.png'>
  <%= link_to 'Follow another twitter user', new_twitter_user_path, :class => "btn btn-default"  %>
</div>
<br/><br/>

<% @all_tweets.each do |tweet| %>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 ">
      <div class="panel panel-primary">
        <div class="panel-heading">
          @<%=tweet[:id] %>
        </div>
        <span>
          <img src="https://g.twimg.com/dev/documentation/image/favorite_on.png">
          <%=tweet[:fav_count] %>
        </span>
        <span>
          <img src="https://g.twimg.com/dev/documentation/image/retweet_on.png">
          <%=tweet[:rt_count] %>
        </span>
        <div class="panel-body" style="min-height: 130px; max-height: 130px;" >
          <%=auto_link tweet[:tweet] %>
        </div>
      </div>
    </div>

<% end %>

app/views/twitter_users/new.html.erb
<h1>Follow a New Twitter</h1>

<%= render 'form' %>

<%= link_to 'Back', twitter_users_path %>

app/views/twitter_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @twitter_user.user_id %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @twitter_user.twitter_id %>
</p>

<%= link_to 'Edit', edit_twitter_user_path(@twitter_user) %> |
<%= link_to 'Back', twitter_users_path %>